-- MySQL Script generated by MySQL Workbench
-- Sat Nov 18 11:16:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shop` DEFAULT CHARACTER SET utf8 ;
USE `shop` ;

-- -----------------------------------------------------
-- Table `shop`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name_category` NVARCHAR(50) NULL,
  `url_category` NVARCHAR(100) NULL,
  `id_parent` INT NULL,
  `seo_keywords_category` NVARCHAR(255) NULL,
  `seo_description_category` NVARCHAR(255) NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `name_product` NVARCHAR(50) NULL,
  `description_product` NVARCHAR(50) NULL,
  `id_pictures` INT NULL,
  `count_product` INT NULL,
  `price_product` DECIMAL(25,2) NULL,
  `seo_keywords_product` NVARCHAR(255) NULL,
  `seo_description_product` NVARCHAR(255) NULL,
  `manufacturer_product` NVARCHAR(50) NULL,
  `id_category` INT NULL,
  `type_product` NVARCHAR(50) NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`optoins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`optoins` (
  `id_optoin` INT NOT NULL,
  `name_optoin` NVARCHAR(50) NULL,
  PRIMARY KEY (`id_optoin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shop`.`product_option`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shop`.`product_option` (
  `id_product_option` INT NOT NULL,
  `id_product` INT NULL,
  `id_option` INT NULL,
  `value_option` NVARCHAR(50) NULL,
  PRIMARY KEY (`id_product_option`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
